version: "3.8"
services:
  postgres-db:
    container_name: jdwyer
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: jdwyer
      POSTGRES_PASSWORD: jdwyer
      POSTGRES_DB: jdwyer
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5450:5432"

volumes:
  postgresql_data:
    driver: local