spring:
  application:
    name: jdwyer

  datasource:
    url: jdbc:postgresql://localhost:5450/jdwyer
    driver-class-name: org.postgresql.Driver
    username: jdwyer
    password: jdwyer
  flyway:
    enabled: true
    locations: classpath:db/migration
    jpa:
      generate-ddl: false
      hibernate:
        ddl-auto: none
    server:
      port: 8080